# Generated by Django 3.0.5 on 2020-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfl',
            name='conference',
            field=models.CharField(choices=[('AFC', 'American Football Conference'), ('NFC', 'National Football Conference')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nfl',
            name='divisions',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=50, null=True),
        ),
    ]
